import math
import pygame

RES = WIDTH, HEIGHT = 1600, 900
FPS = 60

PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.003
PLAYER_SIZE = 0.1
PLAYER_ROT_SPEED = 0.002
MOUSE_SENSITIVITY = 0.002

MAX_DEPTH = 20
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_WIDTH = WIDTH // 2
DELTA_ANGLE = FOV / NUM_RAYS
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS